### ISSUE TITLE
Param seems to be max_tokens instead of max_tokens_to_sample

### ISSUE THREAD

**Issue by aus70** [connorjacobsen/anthropic#2]
Hi

from the Anthropic docs it seems that the maximum number of generated token should be set by the `max_tokens` parameter, while `max_tokens_to_sample` is being used in the code: Am I missing anything? Thanks.

**Comment by connorjacobsen** [comment]
It's possible the API has changed since the original implementation or the implementation is just wrong. I can look into it and put up a fix shortly.

Update:
It looks like it's correct for the text completions API and different for the messages API: https://docs.anthropic.com/claude/reference/complete_post

**Comment by connorjacobsen** [comment]
@aus70 Just published v0.2 with Messages API support.

**Comment by upccjesse** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
grimd34th, @wanglun, @Dujskan, @getabo, @taeguk, @mirobeka, @codeFree1991, @xeoneux, @CYONEA, @sunlight2728, @mounb, @m-nemati, @kabirugad, @ClaudGross, @iamafresh, @LeeSen11, @matheusmoreira, @zhygit, @TimvanScherpenzeel, @qisedao0215, @GregoryTrzonkowski, @gigibox, @sun0720, @Edward-Li, @jclub2434, @blrsn, @opengineer, @DerekMarshall, @Moridi, @Alkesst, @1549002514, @beodeulsoft, @bugthesystem, @hl3w22bupt, @matt-wesley, @ErikYoung89, @bhaltair, @crlsgms, @pik694, @99Percent, @OXOYO, @jl0x61, @FineJade77, @smfarzaneh, @peterpossamai, @baleato, @iquabius, @snakies, @rjzou, @polouervsantosu, @ib0b, @crvn-p, @datacruiser, @harekumar, @jna29, @Leonab, @srijanshukla18, @ii0, @nimble-123, @mattott, @hasanlussa, @estintax, @NaokiKojima4994, @addyxvii, @redev7, @david-resnick, @immense055, @thiiagoms, @shinchong, @ajaybirla, @robotparty, @QGB, @danlutz, @leonardAta, @waynewyang, @mzf, @clot, @hypnopump, @szpasztor, @marcopesani, @maxbaluev, @alanbonachella, @shaoxul, @Luodian, @Mosesofmason, @RafaelC457ro, @zhuangzaiku, @shiyunsheng, @Thinker024, @cslarson, @miloradbozic, @psy0231, @mstansbu, @kexinrong, @altonzheng, @whz-pa, @pomed, @rotvalli, @notfreedude
